### ISSUE TITLE
Missing build.xml

### ISSUE THREAD

**Issue by cb-shivamagarwal** [spockframework/spock-example#71]
Readme.md says there is an example of running Spock using Ant but it seems that the Ant example was deleted in a PR earlier. May you please add the example again or let us know the reason behind deleting the example ?

**Comment by leonard84** [comment]
Honestly, I consider ANT to be outdated and didn't want to maintain the `build.xml` anymore, that is why I deleted it. And apparently I missed a mention of it in that commit.

If you are still using ANT, take a look at https://github.com/junit-team/junit5-samples/blob/r5.9.1/junit5-jupiter-starter-ant/build.xml, since Spock 2.x is a JUnit Platform engine, this combined to the [old build.xml](https://github.com/spockframework/spock-example/blob/6218e48cca61794055663118b7b3bb2566fea7f2/build.xml) should give you the necessary building blocks to get it to work.

What is the reason for still using ANT?

**Comment by cb-shivamagarwal** [comment]
Thank you @leonard84 . I was just curious that there is no example of ANT even though README mentions it.
